language: java
jdk:
- openjdk8
before_install:
- openssl aes-256-cbc -K $encrypted_b03e57a992da_key -iv $encrypted_b03e57a992da_iv
  -in signingkey.asc.enc -out signingkey.asc -d
install: mvn --settings .maven.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true
  -B -V
after_success:
- gpg --batch --yes --passphrase=$PASSPHRASE --keyring=$TRAVIS_BUILD_DIR/pubring.gpg
  --no-default-keyring --import signingkey.asc
- gpg --batch --yes --passphrase=$PASSPHRASE --allow-secret-key-import --keyring=$TRAVIS_BUILD_DIR/secring.gpg
  --no-default-keyring --import signingkey.asc
- echo XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
- gpg --list-secret-keys --keyring=$TRAVIS_BUILD_DIR/secring.gpg --no-default-keyring
- echo YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
- echo PASSPHRASE chars
- echo -n $PASSPHRASE | wc -m
- echo PASSPHRASE bytes
- echo -n $PASSPHRASE | wc -c
- echo SONATYPE_PASSWORD chars
- echo -n $SONATYPE_PASSWORD | wc -m
- echo SONATYPE_PASSWORD bytes
- echo -n $SONATYPE_PASSWORD | wc -c
- echo SONATYPE_USERNAME chars
- echo -n $SONATYPE_USERNAME | wc -m
- echo SONATYPE_USERNAME bytes
- echo -n $SONATYPE_USERNAME | wc -c
- echo ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
- mvn clean deploy --settings .maven.xml -DskipTests=true -Dgpg.executable=gpg -Dgpg.keyname=B6CB59E9615DE082C5469895235B3F3F808E8AFD
  -Dgpg.passphrase=$PASSPHRASE -Dgpg.publicKeyring=$TRAVIS_BUILD_DIR/pubring.gpg -Dgpg.secretKeyring=$TRAVIS_BUILD_DIR/secring.gpg
  -B -U -Prelease
before_deploy:
- mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
- export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep
  -v '\[')
deploy:
  provider: releases
  api_key:
    secure: QvYOeVzY0uPxFYpp+uMaHsKD6Pvb/mEC1s2E12y4ZSLsN84jVlLZ92FWnZzlhtmzNVahQu6GGlEMcINMPySWQmpIBMal8BebYdRF2yosYO/XXy/vRbdMNkW1/6EgDPWn2hHw6VWnU8f9i9YbjfIhqGeSVGmSYHciSrEvJ4JB9XS3AIl92mt6PHrErV2dDhT0eKSRb6NUiCd9TLu6isZPAUiFjCVepOtzJK1S/WngcPI49jL4pV4kRnDcM37Ed1hE0EMQbhPlygJ724PLXtt96lxt3pZt+dS86xQtmsa3Q0Miz6dA2b853Wp99U2sQffHt2FQ+cHM0ECAeNRqxnpkJpIYcrY/wyaayHHtQkRy571D/jegBidfovM/VLD5lbYPaNkkqRXiFhfbpI/Cu5i5RC8+uPTXMwEiMioLB1oGotjy5H2PSN9UR3yIBqN5BNEfmkNwhQ3o3R0xb7SK031/4N5b2lPOdIT6nCzBUx+MvIQ36FfT5QxwsW54sVY2k2MQM1wqo41YZviUkNkTFYjes2z+Dm1lMd7LaMhS9LZoKVZ2kiYD0O1cRkWbHIqEV7/1kY7r0ma1HRMJj1dpCt+dLezpb/qaUgCy80XZRbqFid+PDDW5duIp6kHWvGFUa2cNl3+eGde0bnf94UMClVXyQVrIEnHTrmWf6e+r7eX+UUw=
  file:
  - target/database-reader-$project_version.jar
  skip_cleanup: true
  on:
    repo: intresrl/database-reader
  name: "$project_version"
notifications:
  email: false
env:
  global:
  - secure: qn/bZV4X3PC4thsjjHLQiMIcqUUgPkyljGcaA1cTgsuaiXcp2d6URLUVbCCBn23mNZCU0R7m608R8rL6KhS8izezJO6m1+ADrE1850Ocs9KVorF+weAZx32CclW8GrzfgV5j5X9PKUkkKn2R2VjPw2JchUSs1NYApN9N1nq0lPcuH5xnkkTyoO1LdeaQUc1OIOr9LsJPg13KpPRFZnzDTOe2PF5pmS0vs+ZvfvcnMi0YzIajSop9uES89m5E7vWEKYasm24j1tdn0llmJTIpimqO356bNSkjXm5kCFA8WifCkU34hKHL7+AYn6dQnLlr6uQ1VRaRqz0htQ6rbenmDkDEShQdft3wEJqUH2wvwhbiqhQhpNl6mrensmFTM1U78U/plsU4C9NYvunEzMMw+qljEdEZMPAThUDyP49HPQlgXzvDqbH+fHziy6m1kMTolNd1eRXRI1yfSavSkBAIeITL9BAjNLzXCxxvNTj1abZGqZKKdc623aiQcVN+rj4SfmSb1GdR2CoKzX3PnwSeTD4fI3nCx2h+xDxySwxEyb0cDr0RumPlP781PZiZL5HuE2LZ029VoQEyBeqj8zsFruce6JVNmDz0nt4EVtZ3JmEvJf1HWH79mjh6oEDHF1vnPV8+JqJwrpPlA2h9gLV9z9rZ53Jv2UQXcLYORbXsqlA=
  - secure: UM8eaEwJt4jYPQ9vXUtaFUBwzZch0Lg7rPuoisGi55Ezk30CCXVIkD3gkq8LDZGkXoHvWvYtzQYLJqkL00ZGHr7YPBwFjscP2ZK0D4mK/tOBSKqDfbnwV6M+tCc2pIgwR0pbCDeYnV2U1aYDO+P7B8JciNuE4kvGxmepa4abjL9GA+CPLu3SIGBj5ia443yC/IlJSw/ckvFjxE/HS4G5OCYvKE+oa4oPN4cA3EiF60XVzs2U0lrhyb+oGWtB18aJsvkoFsUOMvJJfmlJ9LziJXmgiVGhQPlX1zH+9/oSBwnJtdDySRX2ukN7MbACn8VdT9d0z1QiMVpO3hlcRJiNA7wDPKLv6eUAk9uW0SCOD4EoHR64FmOKf/SNZGLl5n95RnBxUx75FbkuCoFkvtissedOg/znElhr40iCjPzY49mAEE7zBHvvEYr+Y+xMabHtK8w5L0mkjsF9RRp2cLQo6dydgBCR0y0lLhgB03plos0d4CmPKkV+28wNMuwe14rrzcf2fYlIXuHRY7llR4rZzVD5hp+WVs128TyK6e0vvsL9yeLccHsnHaR72LPCBeXE7JMws666x1wgrKMv/IS4Mfl3N0Pqfz0n3QTEYV11xJ61npiOj2SAu5kHJDTSWflmprOjte0hOJyLQezwCTAJjk6I3U5Ii8muG4tlpR8WnKs=
  - secure: Aa1jwoQuvvfE8LIMZKxigasNcbURkEiMBhTwdGJf3+dRJfXEiDhb/hzh6IPMxLzTft4HVKtVVm0iWo/K96I+U/ZNYjwLt6B1C8EFuT+VQcEW59eIpWNo1cQmyxYFe4zFjIycsYA00C5v40vQF130/t9dFaHEer1/5m80SyGTbyM3NDYZvriS7wjE3zjTWTR2l8gRp4B8AXM+IHPbpbbqN7neZcVLTADVORYhQRmb/kIV2LXKYDctaAF49eSkXwwuXUUON0DjjRo3GncQhyGfCqZhPKgmoHDgRBAywZuwnWfkAsCpIRaEIxWVyW2mrAFh/XEXaqeJrW0W3gHq4c2kx1xnkpOpNB38Ujg7VoafCedAW9MBUH7FA91uR7AiDyvHtgpZ/x0IymmIAyYepe4Ve6GuOIXElWUqUwABxohoeHviX61PbwEW8tiFYtB6URCvhDtN/Wr1xGD5usCgPQ7esIswyBX1Ljkdmy6NioUugoTxS7JDFBqM1g46AYzz7wx2ILkEQxCvIzjPejbEEvdfhuJms6C+hx3K1QAAW4utYvqtmnW02kU7tg7tbCEaAra3CwOojOHHmYDSAR4uhBjyIePdjvDJwXhqzTIRuBXvACVBUXU8+08tYfrYh7xKbEU6eNMrM8AvXJ5gJk8cCLWJnVewLNsWxJWw1byPc62RJBo=
