language: java

jdk:
- openjdk8

## export GPG details
before_install:
- openssl aes-256-cbc -K $encrypted_b03e57a992da_key -iv $encrypted_b03e57a992da_iv -in signingkey.asc.enc -out signingkey.asc -d

install:
  mvn --settings .maven.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V

after_success:
  - gpg --batch --yes --passphrase=$PASSPHRASE --keyring=$TRAVIS_BUILD_DIR/pubring.gpg --no-default-keyring --import signingkey.asc
  - gpg --batch --yes --passphrase=$PASSPHRASE --allow-secret-key-import --keyring=$TRAVIS_BUILD_DIR/secring.gpg --no-default-keyring --import signingkey.asc
  - echo XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  - gpg --list-secret-keys --keyring=$TRAVIS_BUILD_DIR/secring.gpg --no-default-keyring
  - echo XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  - mvn clean deploy --settings .maven.xml -DskipTests=true -Dgpg.publicKeyring=$TRAVIS_BUILD_DIR/pubring.gpg -Dgpg.secretKeyring=$TRAVIS_BUILD_DIR/secring.gpg -B -U -Prelease

before_deploy:
- mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
- export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')

deploy:
  provider: releases
  api_key:
    secure: QvYOeVzY0uPxFYpp+uMaHsKD6Pvb/mEC1s2E12y4ZSLsN84jVlLZ92FWnZzlhtmzNVahQu6GGlEMcINMPySWQmpIBMal8BebYdRF2yosYO/XXy/vRbdMNkW1/6EgDPWn2hHw6VWnU8f9i9YbjfIhqGeSVGmSYHciSrEvJ4JB9XS3AIl92mt6PHrErV2dDhT0eKSRb6NUiCd9TLu6isZPAUiFjCVepOtzJK1S/WngcPI49jL4pV4kRnDcM37Ed1hE0EMQbhPlygJ724PLXtt96lxt3pZt+dS86xQtmsa3Q0Miz6dA2b853Wp99U2sQffHt2FQ+cHM0ECAeNRqxnpkJpIYcrY/wyaayHHtQkRy571D/jegBidfovM/VLD5lbYPaNkkqRXiFhfbpI/Cu5i5RC8+uPTXMwEiMioLB1oGotjy5H2PSN9UR3yIBqN5BNEfmkNwhQ3o3R0xb7SK031/4N5b2lPOdIT6nCzBUx+MvIQ36FfT5QxwsW54sVY2k2MQM1wqo41YZviUkNkTFYjes2z+Dm1lMd7LaMhS9LZoKVZ2kiYD0O1cRkWbHIqEV7/1kY7r0ma1HRMJj1dpCt+dLezpb/qaUgCy80XZRbqFid+PDDW5duIp6kHWvGFUa2cNl3+eGde0bnf94UMClVXyQVrIEnHTrmWf6e+r7eX+UUw=
  file:
      - target/database-reader-$project_version.jar
  skip_cleanup: true
  on:
    repo: intresrl/database-reader
  name: $project_version

notifications:
  email: false
